### ISSUE TITLE
Player controller just crashes after running client

### ISSUE THREAD

**Issue by SoheilKhatibi** [RoboCup-Humanoid-TC/webots#115]
On release branch, the player controller of the robot just crashes after running the `client` or `test_client`.

Command I used to run it:
```
./client 127.0.0.1 10002
```

**Comment by medrimonia** [comment]
Dear Soheil, a minimum of additional information would be appreciated. How do you notice that the player controller crashed?
Is there any error message provided?

**Comment by SoheilKhatibi** [comment]
There are just 2 warnings about the request from the client side. Does it work okay for you?
Here is the screenshot of what I get:
![Screenshot from 2021-05-20 10-57-58](https://user-images.githubusercontent.com/31012373/118929995-740aeb80-b95a-11eb-83d1-a350aefd3dc7.png)

**Comment by medrimonia** [comment]
Are you certain that you followed the following procedure?

1. `git clean -xfd` _after_ checkout of the release branch
2. `make` in webots folder
3. `make` in `projects/samples/contests/robocup/controllers/player`

This error is reached if the `getNodeType` is not valid which is something that might be impacted if the build is not 'clean' (see #104 )

**Comment by SoheilKhatibi** [comment]
After re-building the project the problem is resolved. Thanks. I had built it after checking out to release branch, but maybe after the changes it was needed again.
