### ISSUE TITLE
Declaring a Winner of a Match - Case: Winner

### ISSUE THREAD

**Issue by MaikePaetzel** [RoboCup-Humanoid-TC/webots#12]
Setup:

1. Game is started by the AutoReferee
2. One goal is scored for team red (either by kicking the ball into the goal, by sending the respective command to the GameController, or by using the UI of the GameController to score a goal)
3. The game time passes

Expected outcome: 

1. AutoRef declares team red winner of the match after 10 minutes in the second half have expired
2. Game state switches to FINISH
3. Game log contains the information (with real and simulated timestamp): winner of the match with final game score, game state FINISH

**Comment by medrimonia** [comment]
Automatically tested and passing in `results/win`, game log content is not tested.
