### ISSUE TITLE
Declaring a Winner of a Match - Case: Draw

### ISSUE THREAD

**Issue by MaikePaetzel** [RoboCup-Humanoid-TC/webots#13]
Setup:

1. RoundRobin Game is started by the AutoReferee
2. One goal is scored for team red (either by kicking the ball into the goal, by sending the respective command to the GameController, or by using the UI of the GameController to score a goal)
3. One goal is scored for team blue
4. The game time passes

Expected outcome: 

1. AutoRef declares the game to be a draw
2. Game state switches to FINISH
3. Game log contains the information (with real and simulated timestamp): match ending in a draw with final game score, game state FINISH

**Comment by medrimonia** [comment]
Automatically tested and passing in `results/draw`, game log content is not tested.
