### ISSUE TITLE
referee: rotate_along_z does not rotate along z

### ISSUE THREAD

**Issue by timonegk** [RoboCup-Humanoid-TC/webots#137]
**Describe the Bug**
In the auto-referee, the function `rotate_along_z` currently converts the rotation to a quaternion, multiplies it with the unit quaternion, and converts it back to axis angle. This does not actually rotate along the z axis.
For our robot, that's a problem because it falls down when it is spawned on the other side of the field.

**Screenshots**

https://user-images.githubusercontent.com/25013222/120329702-65beb700-c2ec-11eb-8b71-39031319916f.mp4

**Comment by omichel** [comment]
That's correct. For some reason, the rotation quaternion was commented out and the unit quaternion was used instead. I will investigate and fix it as soon as possible. Did you try to uncomment the Z rotation quaternion to see if that resolves your problem?

**Comment by timonegk** [comment]
Okay, [0,0,0,1] is not actually the unit quaternion, because the library uses the wxyz order. That actually is a rotation of 180° degrees around the z axis, but the result is wrong because the rotation is not around the global z axis. The commented out line rotates around the x axis, which is also wrong.

**Comment by timonegk** [comment]
I thin rotate_along_z should be called before applying the rotation from the startingPose.

**Comment by timonegk** [comment]
So that would be keeping rz as [0,0,0,1], but switching the arguments of qmul, that change fixes the issue.

**Comment by omichel** [comment]
Fixed in #139.
