### ISSUE TITLE
`player` should not disable the actuators when a robot is penalized

### ISSUE THREAD

**Issue by timonegk** [RoboCup-Humanoid-TC/webots#143]
**Describe the Bug**
When the robot is penalized, it is set to the side of the field and its actuators are disabled. But when the robot is not in a stable position when it is penalized, it cannot reset itself to a stable position and will fall again when the auto referee stops holding it up. The fall results in another penalty and so on.

**Expected behavior**
The robot should be able to move its actuators when it gets penalized so that it can recover from unstable positions.

**Comment by medrimonia** [comment]
This issue is forbidding some teams to get back into the game once they are penalized. It should then be solved as soon as possible.

To the best of my understanding, waiting 5 seconds after a penalty before starting to penalize the robot should be sufficient to solve the problem.

**Comment by omichel** [comment]
> To the best of my understanding, waiting 5 seconds after a penalty before starting to penalize the robot should be sufficient to solve the problem.

Do you mean waiting 5 seconds after a penalty before starting to disable the actuators of the robot?

**Comment by medrimonia** [comment]
Yes, that's exactly what I mean. This would allow robots to set their position properly before disabling the actuators.

**Comment by omichel** [comment]
This should be fixed now in #148.

**Comment by medrimonia** [comment]
@timonegk Could you confirm that this solves your problem?

**Comment by omichel** [comment]
According to https://github.com/RoboCup-Humanoid-TC/webots/pull/148#issuecomment-854718740, I believe this issue can be closed. Feel free to re-open it if needed.
