### ISSUE TITLE
Displayed time and GameController time get out of sync when the udp bouncer is used

### ISSUE THREAD

**Issue by timonegk** [RoboCup-Humanoid-TC/webots#144]
**Describe the Bug**
When `use_bouncing_server` is set to true in `game.json`, the time of the GameController and the time overlay in webots get out of sync when the realtime factor is not close to one. The GameController seems to use the correct time as it corresponds to the simulated time in webots, but the overlay is significantly slower.

**Steps to Reproduce**
1. Run `./webots ./projects/samples/contests/robocup/worlds/robocup.wbt`
2. Have a low real time factor (or go through the simulation step by step)
3. See that the time of the GameController and the overlay diverge

**Expected behavior**
They should be in sync like when `use_bouncing_server` is false.

**Additional context**
Maybe there is an issue with our setup? But I don't really think so since the issue could be reproduced without our software components.

Commit id of webots is 8a3a920 (current release branch).
Commid id of the GameController is 5e72ce8 (current master).

**Comment by medrimonia** [comment]
@MaikePaetzel This might be due to GC messages accumulating in the `udp_bouncing_server`. I am unsure whether there is currently a mechanism to check if we are starting to have delay in the messages.
I had an out-of-sync feeling when benchmarking the robots of teams.
