### ISSUE TITLE
Game crashes if a team has no penalty kicker available

### ISSUE THREAD

**Issue by medrimonia** [RoboCup-Humanoid-TC/webots#147]
When launching game in penalty mode against an 'empty' team, we get the following error:
```
 Traceback (most recent call last):
  File "referee.py", line 2120, in <module>
    if not kicker['outside_goal_area'] and not kicker['inside_own_side']:
TypeError: 'NoneType' object is not subscriptable
```

This could also occur in case a team has too much red cards, in that case the other team should play the next trial directly.

**Comment by omichel** [comment]
It should be fixed in #149.
