### ISSUE TITLE
Ball Being out of Play - touchline with throw-in

### ISSUE THREAD

**Issue by MaikePaetzel** [RoboCup-Humanoid-TC/webots#15]
Setup:

1. Game is in state PLAY
2. Ball is touched by player of team red
3. The ball entirely crosses one of the touchlines

Expected outcome: 

1. ball is replaced on the centerline at the position it left the field; 
2.  AutoRef declares THROW-IN for team blue
3. Game log contains the information (with real and simulated timestamp): position at which the ball left the field + robot last touching the ball (identified by team and number), position of the ball after being re-spawned on the field line, throw-in + team it was awarded to

**Comment by medrimonia** [comment]
Automatically tested and passing with several scenarios in `game_interruptions/corner`.
