### ISSUE TITLE
`player` controller dies when a client connects in game state "Playing"

### ISSUE THREAD

**Issue by timonegk** [RoboCup-Humanoid-TC/webots#153]
**Describe the Bug**
The `player` controller currently dies when our software connects after the game state changed to playing. This is not a problem during the actual games but it is annoying when testing. The `player` also does not seem to terminate correctly because the port is still allocated after the `player` has died.

**Steps to Reproduce**
1. Start the RoboCup environment
2. Wait until the game state changes to playing
3. Connect to the player API

**Comment by medrimonia** [comment]
I tried connecting in "PLAYING" state with multiple instances of the default clients and did not experience any issue. Is it still crashing with the latest release? If it is, is there any error message that might provide a hint?

**Comment by SammyRamone** [comment]
I tested it, it works with the current version of webots. Can be closed in my opinion.

**Comment by medrimonia** [comment]
Thank you for the feedback!
