### ISSUE TITLE
Penalty goals are awarded for the wrong team

### ISSUE THREAD

**Issue by Flova** [RoboCup-Humanoid-TC/webots#161]
**Describe the Bug**
If the team kicks a goal during the penalty shootout it's accounted for in the wrong team. 

**Steps to Reproduce**
* Kick a goal using the robot behavior in a penalty shootout

**Expected behavior**
* The goal should be counted correctly

**Screenshots**
https://streamable.com/fk88t8

**Comment by Flova** [comment]
The score in the game controller is correct tho

**Comment by Flova** [comment]
![image](https://user-images.githubusercontent.com/15075613/120895667-5e661900-c61e-11eb-882b-fcbdb53172c0.png)

**Comment by medrimonia** [comment]
One of the potential explanations is that the `update_team` seems to be only called at end of half and not between penalty shootouts. From my point of view, `update_team` should be called each time `flip_side` is called and not only on specific situations.

I don't now if there is something else to be done about this or not.
