### ISSUE TITLE
Penalty kicker is always robot 1

### ISSUE THREAD

**Issue by medrimonia** [RoboCup-Humanoid-TC/webots#172]
Current implementation of `is_penalty_kicker(team, id)` does not take into account the fact that other robots of the same team might have received a red card.

The penalty kicker should always be the player with the lowest id of the team.

**Comment by omichel** [comment]
What if player number 1 has no red card, but has currently a 30 second penalty removal? Shall we decide that the penalty kicker is number 2 in that case?

**Comment by medrimonia** [comment]
The penalty kicker should be chosen after setting state to `SET`. In theory, the GameController should remove the penalty of all robots when entering state `SET` (if it doesn't, that's a bug). So no player should be penalized  when this function is called.

**Comment by omichel** [comment]
I believe that #177 now fixes this issue.

**Comment by medrimonia** [comment]
Perfect, I will add automated test scenarios and merge it afterwards since it is not urgent I think.
