### ISSUE TITLE
Robot Positioning - valid configuration

### ISSUE THREAD

**Issue by MaikePaetzel** [RoboCup-Humanoid-TC/webots#2]
Setup:

1. In the config.json file, a legal position for a robot is provided

Expected outcome: 

1. The robot is spawned at the beginning of the game at the position indicated in the config.json file 
2. Once the state is changed to READY, the robot can progress positioning itself on the field.
3. Game log contains the information (with real and simulated timestamp): Robots being spawned + position, game state READY

**Comment by medrimonia** [comment]
Covered by `test_initial_positions`.

**Comment by medrimonia** [comment]
Covered automatically by the scenario `positioning/initial`.
