### ISSUE TITLE
Ball Being out of Play - Own goal, advanced case

### ISSUE THREAD

**Issue by MaikePaetzel** [RoboCup-Humanoid-TC/webots#20]
Setup:

1. Game is in state PLAY
2. Ball is touched by player of team red
3. The ball entirely crosses the goal line on the side of team red

Expected outcome: 

1. Ball is replaced on the corner of the touchline and goal line on side the ball left the field
2. AutoRef declares CORNER KICK team blue
3. Game log contains the information (with real and simulated timestamp): position the ball left the field + robot last touching the ball (identified by team and number), position the ball was re-spawned, corner kick and team it was awarded to

**Comment by medrimonia** [comment]
Automatically tested and passing with several scenarios in `game_interruptions/corner`.
