### ISSUE TITLE
Display simulation time in replay

### ISSUE THREAD

**Issue by medrimonia** [RoboCup-Humanoid-TC/webots#206]
Currently it's hard to make the link between the logs and the replay of the games because there is no common clock. It would be nice to have a small clock showing the simulation time in the display.

A very nice touch would be to have the option of toggling its display (I don't know if that's possible with the html replay).

**Comment by omichel** [comment]
Another nice possibility to handle this issue would be to start the recording of the animation at time step 0, so that the slider bar of the resulting animation would display the actual virtual time.

**Comment by medrimonia** [comment]
Yes I think that would be even better I agree because this wouldn't be confusing for the audience since it is a feature useful only for teams and developers.

**Comment by omichel** [comment]
> 
> 
> Yes I think that would be even better I agree because this wouldn't be confusing for the audience since it is a feature useful only for teams and developers.

OK, in that case, I will rework #212 to take this into account and remove the display of the virtual time.
