### ISSUE TITLE
Bug in udp_bouncer.py

### ISSUE THREAD

**Issue by i-khokhlov** [RoboCup-Humanoid-TC/webots#222]
**Describe the Bug**
I suppose that one line in udp bouncing server was misssed. 
For blue team:
https://github.com/RoboCup-Humanoid-TC/webots/blob/7f8b5b34fac59398a42c4b11f08e96cc6af7d191/projects/samples/contests/robocup/controllers/referee/udp_bouncer.py#L99-L102

For read team:
https://github.com/RoboCup-Humanoid-TC/webots/blob/7f8b5b34fac59398a42c4b11f08e96cc6af7d191/projects/samples/contests/robocup/controllers/referee/udp_bouncer.py#L105-L108

**Steps to Reproduce**
Lunch the game with red team. 

**Additional context**
I'm getting this error when udp bouncing receive message:
```
python3 udp_bouncer.py game.json 
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "udp_bouncer.py", line 106, in on_queue_update
    if client != current_package[1]:
UnboundLocalError: local variable 'client' referenced before assignment
```

**Comment by MaikePaetzel** [comment]
Thanks for spotting and fixing it, I merged your PR!
