### ISSUE TITLE
Robot positioning - Illegal position in the end of READY (1)

### ISSUE THREAD

**Issue by MaikePaetzel** [RoboCup-Humanoid-TC/webots#25]
Setup:

1. In the config.json, the player is positioned in a valid position outside the field of play
2. The robot walks into the field and comes to stand on the opponent's side of the play at the end of the READY phase

Expected outcome:

1. The robot is spawned at the beginning of the game.
2. The game state changes to READY
3. The game state changes to SET
4. The robot is penalized as soon as the state changes to SET
5. The robot is respawned at the penalty position
6. The game state changes to PLAY
7. The penalty is removed from the robot again
5. Game log contains the information (with real and simulated timestamp): Robots being spawned + position,  game state READY, game state SET, robot (identified by team and number) penalized + type of penalty, robot (identified by team and number) re-spawned at penalty position, game state PLAY, robot (identified by team and number) penalty ended

**Comment by medrimonia** [comment]
Manual test available in `positioning/ready`.
