### ISSUE TITLE
Direct Freekick without team happens and freezes autoreferee

### ISSUE THREAD

**Issue by timonegk** [RoboCup-Humanoid-TC/webots#261]
**Describe the Bug**
Sometimes, when a free kick is granted, there is no team associated with the free kick (at least in the display). Then, the secondary state time in the game controller stops running and the auto referee no longer does anything. Logs and videos are attached. The issue now occurred three consecutive times while simulating test games.

**Screenshots**
First game: https://streamable.com/vvc6es
Log: [referee_log.1.txt](https://github.com/RoboCup-Humanoid-TC/webots/files/6703839/referee_log.1.txt)

Second game: (I don't have a video)
Log: [referee_log.2.txt](https://github.com/RoboCup-Humanoid-TC/webots/files/6703855/referee_log.2.txt)

Third game: https://streamable.com/kihjnm
Log: [referee_log.3.txt](https://github.com/RoboCup-Humanoid-TC/webots/files/6703859/referee_log.3.txt)

(To finish the game, I manually changed the state to Finished, this is not done automatically by the referee.)

**Comment by timonegk** [comment]
In the GameController GUI, the free kick is shown for one of the teams.
![Bildschirmfoto von 2021-06-23 19-56-15](https://user-images.githubusercontent.com/25013222/123145493-2c95e480-d45d-11eb-8868-67582e81a53f.png)

**Comment by timonegk** [comment]
Also, the auto referee just moved two robots away from the ball for the free kick, but they were placed in such a way that they are colliding / spawned inside each other.
[referee_log.4.txt](https://github.com/RoboCup-Humanoid-TC/webots/files/6704013/referee_log.4.txt)

**Comment by medrimonia** [comment]
Thanks to your log, I feel that I've found something which should not happen:
```
[2428.824|0459.808] Info: Sending 57553:DIRECT_FREEKICK:7 to GameController.
[2428.824|0459.808] Info: Waiting for GameController to answer to 57553:DIRECT_FREEKICK:7.
[2429.024|0459.808] Info: Waiting for GameController to answer to 57553:DIRECT_FREEKICK:7.
[2429.238|0459.808] Info: Ball in play, can be touched by any player (10 seconds elapsed).
[2429.270|0459.808] Info: New secondary state received from GameController: STATE_DIRECT_FREEKICK, phase 0.
```
We see that we have `Ball in play` (which set `game.interruption_team` to `None`) after sending the `FREE_KICK` but before having the `New secondary state`.
