### ISSUE TITLE
 Robot positioning - Illegal position in the end of READY (2)

### ISSUE THREAD

**Issue by MaikePaetzel** [RoboCup-Humanoid-TC/webots#27]
Setup:

1. In the config.json, the player is positioned in a valid position outside the field of play
2. A robot from the team that does not have kick-off walks into the field and comes to stand inside the center circle in it's own half of the field at the end of the READY phase

Expected outcome:

1. The robot is spawned at the beginning of the game.
2. The game state changes to READY
3. The game state changes to SET
4. The robot is penalized as soon as the state changes to SET
5. The robot is respawned at the penalty position
6. The game state changes to PLAY
7. The penalty is removed from the robot again
5. Game log contains the information (with real and simulated timestamp): Robots being spawned + position,  game state READY, game state SET, robot (identified by team and number) penalized + type of penalty, robot (identified by team and number) re-spawned at penalty position, game state PLAY, robot (identified by team and number) penalty ended

**Comment by SoheilKhatibi** [comment]
Similar to this issue, according to the rules, line 400, the opponents of the team taking the kick-off should stay outside the center circle until it is in play (until it moves at least 5 cm or 10 seconds after the play signal). This also can be included in this issue or a new basic issue can be dedicated to this point.

**Comment by medrimonia** [comment]
Yes, I do agree, I will include this to the list of issues that should be covered.

**Comment by medrimonia** [comment]
Manual test available in `positioning/ready`.
