### ISSUE TITLE
Protobuf is not optimal for sending high resolution images

### ISSUE THREAD

**Issue by omichel** [RoboCup-Humanoid-TC/webots#42]
As stated [here](https://developers.google.com/protocol-buffers/docs/techniques#large-data), protobuf is not well suited for sending large amounts of data. Sending images is indeed tricky (based on sending a string). Moreover, there is a significant performance cost for sending images with protobuf:

1. Copy the image from the camera RGBA buffer into a RGB buffer.
2. Copy the RGB buffer into the protobuf bytes buffer.
3. Send the protobuf packet to the socket (deserialization).

Whereas with a custom network protocol, we could send the directly the RGBA camera image to the socket while converting it to RGB on the fly (custom deserialization), which would save the two copies mentioned above.

But maybe the performance impact of these two copies is not critical.

**Comment by medrimonia** [comment]
Performance of sending the images was analyzed as non-critical with respect to the data transfer from the GPU.
