### ISSUE TITLE
Ball holding - Multi-robot, KidSize

### ISSUE THREAD

**Issue by medrimonia** [RoboCup-Humanoid-TC/webots#54]
This situation include 3 variations: a,b,c when they differ, it is explicitely
specified.

## Setup:

- GameState is READY, ball is in play and the game is a KidSize game
- R1 is at less than 30 centimeters from the ball
- R2 is exactly on the other side of the ball
  - a+b. 30 centimeters away from the ball
  - c. 1 meters away from the ball
- a+c. R1 and R2 are from the same team
- b. R1 and R2 are from opposite team
  
## Procedure:

- 1 seconds elapses with all robots static

## Expected outcome

- a. A free kick in favor of the opposite team is given, no robot is penalized.
- b+c. Free kick is not called, no robot is penalized.

**Comment by medrimonia** [comment]
Automated test is available in `ball_holding/multi_robot_kid`.

**Comment by omichel** [comment]
When a robot holds the ball, a free kick is awarded to the opponent team, but what happens to the faulty robot? Does it get a `BALL_MANIPULATION` penalty and is removed from the game?

**Comment by medrimonia** [comment]
The faulty robot(s) are not penalized, they have to move autonomously out from the ball to proceed with the free kick.
It is tested in the automated scenario.

**Comment by medrimonia** [comment]
All tests are now passing.
