### ISSUE TITLE
Team id is expected to be 1 or 2

### ISSUE THREAD

**Issue by medrimonia** [RoboCup-Humanoid-TC/webots#59]
If I set the `team_id` in the `game.json` to another value that 1 or 2, I end up with the following error:

```
Traceback (most recent call last):
  File "referee.py", line 945, in <module>
    check_penalized_in_field(red_team, 'red')
  File "referee.py", line 571, in check_penalized_in_field
    if game.state.teams[team_id - 1].players[int(number) - 1].secs_till_unpenalized == 0:
IndexError: list index out of range
```
`team_id` is expected to be the unique identifier of a team so it should vary between 0 and 255 according to the current implementation. It will also be important to determine which team has throw-in etc...

**Comment by omichel** [comment]
I believe I fixed it [here](https://github.com/cyberbotics/webots/pull/2888/commits/a566d68f311454cacc82d321e393c66ac1d4d6b9). Please pull the latest version and re-test it. It should work.

**Comment by medrimonia** [comment]
It works great.
