### ISSUE TITLE
Game Setup - second half time

### ISSUE THREAD

**Issue by MaikePaetzel** [RoboCup-Humanoid-TC/webots#6]
Setup:

1. In the game config file, two teams are declared for a normal KidSize match, one team with 4 players, one with 3
2. 10 minutes of game time in the first half elapses

Expected outcome: 

1. The AutoRef calls the first half time to be over
2. The robots respawn on the starting positions at the side of the field
3. The sides of play and the kick-off have flipped in the GameController
4. 15 seconds (real-time) elapse
5. The game state switches to READY
6. After 45 seconds game state switches to SET
7. The ball is placed on the center mark
8. After 5 seconds, the game state switches to PLAY
9. Game log contains the information (with real and simulated timestamp): robots being spawned + position, game state READY, game state set, position of ball being placed, game state PLAY

**Comment by omichel** [comment]
When the time of the first half is over, I send the "FINISH" message to GameController and it seems to work. However, when I send the "READY" message (after 15 seconds), I am getting an "ILLEGAL" answer from GameController for this "READY" message. From the GUI, it seems I should press the "2nd Half" button, but there is no such message in the TCP/IP protocol. Is it missing? Or did I miss something?

**Comment by MaikePaetzel** [comment]
Sorry I missed that part! I thought the GC automatically switches to the second half, but it seems it doesn't (or at least not anymore with setting the half-time break to 0 seconds). I've pushed a fix to this branch: https://github.com/RoboCup-Humanoid-TC/GameController/tree/advanced-autoref-updates
You can now send STATE:SECOND-HALF to explicitly switch to the second half.

**Comment by omichel** [comment]
Thank you!

**Comment by medrimonia** [comment]
Manual test available in `game_phases/second_half`.

**Comment by medrimonia** [comment]
Automatically tested and passing.
