### ISSUE TITLE
Field outside_field might be uninitialized

### ISSUE THREAD

**Issue by medrimonia** [RoboCup-Humanoid-TC/webots#63]
When testing a game in fast mode with a single robot, I sometimes have the following error:

 ```
Traceback (most recent call last):
  File "referee.py", line 1285, in <module>
    check_start_position()
  File "referee.py", line 688, in check_start_position
    blue = check_team_start_position(blue_team, 'blue')
  File "referee.py", line 675, in check_team_start_position
    if not player['outside_field']:
KeyError: 'outside_field'
```

By having a quick look at the code, I think that this might be because in `update_team_contacts`, if there are no contact points this entries are not initialized. So if we use `check_start_position` before robots touched the ground this might lead to an issue.

**Comment by omichel** [comment]
This is fixed in https://github.com/cyberbotics/webots/pull/2888/commits/150b062ef5cd84bee5b2e4bdf5482604fa7a5b1f
