### ISSUE TITLE
Invalid team configuration result in crash of referee

### ISSUE THREAD

**Issue by medrimonia** [RoboCup-Humanoid-TC/webots#69]
Currently, if a team does not provide all the requested fields, the referee crashes with the following message and the simulation keeps going

```
Traceback (most recent call last):
  File "referee.py", line 1044, in <module>
    spawn_team(blue_team, 'blue', game.side_left == game.red.id, children)
  File "referee.py", line 114, in spawn_team
    flip_poses(team['players'][number])
  File "referee.py", line 797, in flip_poses
    flip_pose(player['goalKeeperStartingPose'])
KeyError: 'goalKeeperStartingPose'
```

Even if teams provide invalid configuration files, the referee should not crash. There are 2 acceptable behaviors according to me:

1. The robots with missing keys are not loaded and an explicit error is written. This makes sure that teams are unlikely to miss the error message.
2. Whenever a value is requested that was not provided in the configuration file, the robot gets penalized. While teams might miss this, it penalizes them less.

I think that 1 is easier to implement and is requested anyway in case the file is badly formatted (e.g missing comma). Therefore I would personally aim for this.

In both cases, the game should still go on since the other team has to score against an empty goal.
If no robots were loaded, the game should end and be declared as a draw.

**Comment by MaikePaetzel** [comment]
I agree that it is important for the AutoReferee not to crash if invalid data are provided and I would also prefer solution (1). If the file is entirely wrongly formatted and hence not readable, then no robot would be spawned and the game would continue against an empty field, which I think is a good solution - at least it makes it very easy for teams to spot that they made a mistake if they test it.
