### ISSUE TITLE
Transition to state PLAYING is not automatic after a goal has been scored

### ISSUE THREAD

**Issue by medrimonia** [RoboCup-Humanoid-TC/webots#79]
This issue raises when running the test `results/draw`, the 5 seconds of state are properly elapsed without the AutoRef sending anything to the GameController according to the logs.

```
[0010.655|0117.960] Info: New state received from GameController: STATE_SET.
[0011.063|0124.992] Info: Game interrupted before the end.
```

**Comment by omichel** [comment]
This one is also fixed in the most recent version of https://github.com/cyberbotics/webots/pull/2888
