### ISSUE TITLE
Referee can crash over unexpected messages after a goal is scored

### ISSUE THREAD

**Issue by medrimonia** [RoboCup-Humanoid-TC/webots#80]
When a goal is scored, for a few steps the simulation keeps running and spams the GameController that a goal has been scored. During this period, the following error can occur:
```
Traceback (most recent call last):
  File "referee.py", line 1115, in <module>
    game_controller_send(f'CLOCK:{time_count}')
  File "referee.py", line 344, in game_controller_send
    answered_message = game_controller_send.unanswered[int(id)]
ValueError: invalid literal for int() with base 10: ''
```

Robustness to those message should be increase. A temporary workaround would be to add a 1 second sleep after sending a message indicating that a goal has been scored to avoid this spamming.

**Comment by omichel** [comment]
> When a goal is scored, for a few steps the simulation keeps running and spams the GameController that a goal has been scored. 

This is fixed in https://github.com/cyberbotics/webots/pull/2888/commits/6231831e3540b26654a5b2d2168d749eeb381470
