### ISSUE TITLE
Detection of a Goal Being Scored - Own goal

### ISSUE THREAD

**Issue by MaikePaetzel** [RoboCup-Humanoid-TC/webots#9]
Setup: 

1. Player of team red in front of red’s goal
2. Player kicks the ball entirely over the goal line

Expected outcome: 

1. Goal scored for team blue
2. Game state switches to READY
3. After 45 seconds, the game state switches to SET
4. The ball is spawned at the center mark with team red having kick-off
5. Game log contains the information (with real and simulated timestamp): goal scored + robot scoring the goal (identified by team and number), game state READY, game state SET, the position of the ball being spawned

**Comment by medrimonia** [comment]
This test is now automated and successfully passing  in `scoring/own_goal`.
