### ISSUE TITLE
Time spent in Initial is impacted by real time factor

### ISSUE THREAD

**Issue by medrimonia** [RoboCup-Humanoid-TC/webots#93]
The current implementation of the referee makes the `real_time` waiting (e.g. time spent in initial) as a number of simulation ticks depending on `minimum_real_time_factor`. If the simulation runs significantly slower than this factor this results in a much longer INITIAL phase.

E.g. `minimum_real_time_factor=1`, but the game runs much slower, at 0.2 in average. Then, the INITIAL duration is approximately 10 minutes of real-time while it should be only two.

**Comment by omichel** [comment]
Fixed in https://github.com/RoboCup-Humanoid-TC/webots/pull/91/commits/875c1e6c4ecbb5f10610c1d8f119f9b9355c76cc.
